CREATE DATABASE IF NOT EXISTS banking_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE banking_app;

CREATE TABLE IF NOT EXISTS accounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  account_number VARCHAR(32) NOT NULL UNIQUE,
  customer_name  VARCHAR(100) NOT NULL,
  balance        DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
